import type { GitHubProfile } from "../types";

export const mockProfile: GitHubProfile = {
  user: {
    login: "GuilhermeNantes",
    name: "Guilherme Nantes",
    bio: "Software Developer • Open source enthusiast",
    avatar_url: "https://avatars.githubusercontent.com/u/GuilhermeNantes",
    html_url: "https://github.com/GuilhermeNantes",
    public_repos: 24,
    followers: 142,
    following: 38,
    created_at: "2020-03-15T00:00:00Z",
  },
  repos: [
    {
      name: "github-stats-vercel",
      full_name: "GuilhermeNantes/github-stats-vercel",
      description: "Terminal-style SVG card generator for GitHub profiles",
      html_url: "https://github.com/GuilhermeNantes/github-stats-vercel",
      language: "TypeScript",
      stargazers_count: 18,
      forks_count: 3,
      archived: false,
      fork: false,
      pushed_at: "2026-08-12T00:00:00Z",
      updated_at: "2026-08-12T00:00:00Z",
    },
    {
      name: "forge",
      full_name: "GuilhermeNantes/forge",
      description: "Dev automation toolkit",
      html_url: "https://github.com/GuilhermeNantes/forge",
      language: "Go",
      stargazers_count: 12,
      forks_count: 2,
      archived: false,
      fork: false,
      pushed_at: "2026-07-20T00:00:00Z",
      updated_at: "2026-07-20T00:00:00Z",
    },
    {
      name: "gestur",
      full_name: "GuilhermeNantes/gestur",
      description: "Institutional systems backend",
      html_url: "https://github.com/GuilhermeNantes/gestur",
      language: "TypeScript",
      stargazers_count: 7,
      forks_count: 1,
      archived: false,
      fork: false,
      pushed_at: "2026-06-10T00:00:00Z",
      updated_at: "2026-06-10T00:00:00Z",
    },
    {
      name: "inferno",
      full_name: "GuilhermeNantes/inferno",
      description: "Realtime inference engine",
      html_url: "https://github.com/GuilhermeNantes/inferno",
      language: "Rust",
      stargazers_count: 5,
      forks_count: 0,
      archived: false,
      fork: false,
      pushed_at: "2026-05-01T00:00:00Z",
      updated_at: "2026-05-01T00:00:00Z",
    },
    {
      name: "dotfiles",
      full_name: "GuilhermeNantes/dotfiles",
      description: "Personal terminal & shell config",
      html_url: "https://github.com/GuilhermeNantes/dotfiles",
      language: "Shell",
      stargazers_count: 3,
      forks_count: 0,
      archived: false,
      fork: false,
      pushed_at: "2026-04-15T00:00:00Z",
      updated_at: "2026-04-15T00:00:00Z",
    },
  ],
  languages: {
    TypeScript: 145_320,
    Go: 89_120,
    Rust: 52_300,
    JavaScript: 38_700,
    Shell: 12_400,
    Python: 8_900,
  },
  commits: [
    {
      sha: "8a3f1c2",
      message: "feat: add animation one-shot typing",
      date: "2026-08-12T10:30:00Z",
      repo: "github-stats-vercel",
    },
    {
      sha: "7b2e9d4",
      message: "fix: error SVG shows usage",
      date: "2026-08-11T14:20:00Z",
      repo: "github-stats-vercel",
    },
    {
      sha: "6c1d8a5",
      message: "feat: dracula theme",
      date: "2026-08-10T09:15:00Z",
      repo: "github-stats-vercel",
    },
    {
      sha: "5d4e7b6",
      message: "refactor: split render into modules",
      date: "2026-08-09T16:45:00Z",
      repo: "github-stats-vercel",
    },
    {
      sha: "4f3a2c1",
      message: "chore: bump dependencies",
      date: "2026-08-08T11:00:00Z",
      repo: "forge",
    },
    {
      sha: "3e8b9d2",
      message: "feat: new cli flag parser",
      date: "2026-08-07T15:30:00Z",
      repo: "gestur",
    },
  ],
};
